/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SystemHealthCheck': CronHandler<never>
    'DailyReportGenerator': CronHandler<never>
    'CleanupOldData': CronHandler<never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'TrackEngagement': EventHandler<{ campaignId: string; recipient: string; subject: string; sentAt: string; status: string }, never>
    'SendEmails': EventHandler<{ campaignId: string; campaignName: string; content: { subject: string; bodyTemplate: string; personalizationFields: Array<string>; contentVariations: Array<string>; generatedAt: string }; recipients: Array<string>; scheduledFor: string }, { topic: 'email-sent'; data: { campaignId: string; recipient: string; subject: string; sentAt: string; status: string } }>
    'ScheduleCampaign': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { campaignId: string; status: string; recipientCount: number; message: string }> | ApiResponse<400, { status: string; message: string; errors: unknown }>, { topic: 'campaign-scheduled'; data: { campaignId: string; campaignName: string; subject: string; template: string; recipients: Array<string>; scheduledFor: string } }>
    'GenerateContent': EventHandler<{ campaignId: string; campaignName: string; subject: string; template: string; recipients: Array<string>; scheduledFor: string }, { topic: 'content-generated'; data: { campaignId: string; campaignName: string; content: { subject: string; bodyTemplate: string; personalizationFields: Array<string>; contentVariations: Array<string>; generatedAt: string }; recipients: Array<string>; scheduledFor: string } }>
    'ValidateData': EventHandler<{ pipelineId: string; source: string; data: Array<{ id: number; value: number; normalizedValue: string; category: string; timestamp: string; processedBy: string; transformedAt: string }>; fetchedAt: string; transformedAt: string }, { topic: 'data-validated'; data: { pipelineId: string; source: string; data: Array<unknown>; invalidRecords: Array<unknown>; fetchedAt: string; transformedAt: string; validatedAt: string; stats: { total: number; valid: number; invalid: number; validationRate: number } } }>
    'TransformData': EventHandler<{ pipelineId: string; source: string; data: Array<{ id: number; value: number; timestamp: string }>; fetchedAt: string }, { topic: 'data-transformed'; data: { pipelineId: string; source: string; data: Array<{ id: number; value: number; normalizedValue: string; category: string; timestamp: string; processedBy: string; transformedAt: string }>; fetchedAt: string; transformedAt: string } }>
    'StoreData': EventHandler<{ pipelineId: string; source: string; data: Array<unknown>; invalidRecords: Array<unknown>; fetchedAt: string; transformedAt: string; validatedAt: string; stats: { total: number; valid: number; invalid: number; validationRate: number } }, never>
    'FetchData': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { pipelineId: string; status: string; message: string }>, { topic: 'data-fetched'; data: { pipelineId: string; source: string; data: Array<{ id: number; value: number; timestamp: string }>; fetchedAt: string } }>
  }
    
}